ramls/event_config.raml
src/main/java/org/folio/rest/impl/EventConfigAPIs.java
src/test/java/org/folio/impl/EventConfigAPIsTest.java

Fix status code in the stub impl.

Fix status code

---

pom.xml
ramls/event_template.json
ramls/examples/event_config.sample
src/main/java/org/folio/services/impl/StorageServiceImpl.java

Fix method `findEventConfigById` of service `StorageServiceImpl`

MODLOGIN-64

---

pom.xml

[MODEVENTC-11] Fix security vulnerabilities reported in jackson-databind

---

src/main/resources/templates/db_scripts/populate-event-configs.sql

**Purpose**
Updating reset password email template
Resolve: [MODTEMPENG-27](https://issues.folio.org/browse/MODTEMPENG-27)

MODTEMPENG-27 Reset password email: Entire Reset password URL is not hyperlinked

---

pom.xml
src/main/java/org/folio/rest/impl/EventConfigAPIs.java
src/main/resources/templates/db_scripts/populate-event-configs.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/impl/EventConfigAPIsTest.java

RMB version update to 28.0.0

---

pom.xml

Reverts folio-org/mod-event-config#32

Revert "RMB version changed to 28.1.0"

---

pom.xml
src/main/java/org/folio/rest/impl/EventConfigAPIs.java
src/main/resources/templates/db_scripts/populate-event-configs.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/impl/EventConfigAPIsTest.java

Reverts folio-org/mod-event-config#31

Revert "RMB version update to 28.0.0"

---

pom.xml

Resolves [MODEVENTC-25](https://issues.folio.org/browse/MODEVENTC-25).

[MODEVENTC-25] Upgrade to RMB 31.1.5 and Vert.x 3.9.4

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rest/impl/util/EventConfigHelper.java
src/test/java/org/folio/impl/EventConfigAPIsTest.java
src/test/resources/log4j2-test.properties

Resolves: [MODEVENTC-27](https://issues.folio.org/browse/MODEVENTC-27)

MODEVENTC-27 Upgrade to RMB v32

---

descriptors/DeploymentDescriptor-template.json
pom.xml
src/test/java/org/folio/impl/EventConfigAPIsTest.java

Resolves: [MODEVENTC-30](https://issues.folio.org/browse/MODEVENTC-30)

MODEVENTC-30 Update RMB and Vertx versions

---

pom.xml

Resolves [MODEVENTC-33](https://issues.folio.org/browse/MODEVENTC-33)

MODEVENTC-33 Change version to 2.1.0

---

NEWS.md
pom.xml

Resolves [MODEVENTC-32](https://issues.folio.org/browse/MODEVENTC-32).

[MODEVENTC-32] Release 2.1.0

---

pom.xml

[MODEVENTC-41](https://issues.folio.org/browse/MODEVENTC-41)
_RMB v34 upgrade_

MODEVENTC-41: RMB v34 upgrade

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODEVENTC-45

MODEVENTC-45: Release 2.18.0

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j.properties
src/main/resources/log4j2-json.properties

- Logging should be improved for more productive troubleshooting
Resolves: [MODEVENTC-47](https://issues.folio.org/browse/MODEVENTC-47)
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md

[MODEVENTC-47] Add log4j configuration

---

NEWS.md
pom.xml

[MODEVENTC-48](https://issues.folio.org/browse/MODEVENTC-48)
Release: v2.5.0 (Orchid) - Mod-event-config
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?  
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

Release PR v2.5.0 (Orchid)

---

Dockerfile
Jenkinsfile
pom.xml

_[MODEVENTC-50](https://issues.folio.org/browse/MODEVENTC-50) : Update to Java 17 mod-event-config_
Update the module to Java 17 and identify issues.
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
Changed the java sdk version to 17 wherever applicable

MODEVENTC-50 : Update to Java 17 mod-event-config

---

NEWS.md
pom.xml

MODEVENTC-51 - Poppy release

---

pom.xml

To Upgrade raml and vertex version for Q release.
Ugraded the version as per https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-352

MODEVENTC-53 - Upgrade raml and vertex version for Q release.

---

NEWS.md
pom.xml

MODEVENTC-52 - Release 2.7.0

---

NEWS.md
pom.xml

MODEVENTC-55 - To release 2.7.1

---

NEWS.md
pom.xml

Modeventc 55 - for long live branch

---

.github/workflows/postgres.yml
pom.xml

MODEVENTC-58 - Upgrade RMB version 35.3.0

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODEVENTC-60

MODEVENTC-60: Ramsons release

---

.github/workflows/postgres.yml
Dockerfile
Jenkinsfile
pom.xml

FOLIO-4224 - Java and RMB upgrade

---

NEWS.md
pom.xml

NEWS.md and version upgrade

---

NEWS.md
pom.xml

update pom version
